---
- name: Configure the system
- hosts: all
  sudo: yes
  gather_facts: false

  tasks:
    - name: Update APT package cache
      action: apt update_cache=yes
      become: true

    - name: get the username running the deploy
      local_action: command whoami
      register: logged_in_user

    - include: software.yaml
    - include: git.yaml
    - include: conf.yaml
